Test 1 production.yml
Testing production CI/CD to know if the CI/CD is working well to generate env files

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -21,8 +21,7 @@ jobs:
   #         node-version: 18
   #     - run: npm ci
   #     - run: npm test
-  
-        
+
   # Generates the Env file and pushes to s3 bucket 
   generate-env-file:
     name: generate-env-file
@@ -51,15 +50,14 @@ jobs:
         CRYPTO_ALGORITHM=${{ secrets.CRYPTO_ALGORITHM}}
         CRYPTO_IV=${{ secrets.CRYPTO_IV}}
         CRYPTO_PASSWORD=${{ secrets.CRYPTO_PASSWORD}}
-        DB_DB_NAME=${{ secrets.TEST_DB_DB_NAME}}
+        DB_DB_NAME=${{ secrets.DB_DB_NAME}}
         DB_DIALECT=${{ secrets.DB_DIALECT}}
-        DB_HOST=${{ secrets.TEST_DB_HOST}}
+        DB_HOST=${{ secrets.DB_HOST}}
         DB_NAME=${{ secrets.DB_NAME}}
-        DB_PASS=${{ secrets.TEST_DB_PASS}}
-        DB_PASSWORD=${{ secrets.TEST_DB_PASS}}
+        DB_PASS=${{ secrets.DB_PASS}}
+        DB_PASSWORD=${{ secrets.DB_PASSWORD}}
         DB_URL=${{ secrets.DB_URL}}
-        DB_PORT=${{ secrets.TEST_DB_PORT}}
-        DB_USER_NAME=${{ secrets.TEST_DB_USER_NAME}}
+        DB_USER_NAME=${{ secrets.DB_USER_NAME}}
         DEFAULT_ELECTRICITY_PROVIDER=${{ secrets.DEFAULT_ELECTRICITY_PROVIDER}}
         DEPLOYMENT_PREFIX=${{ secrets.DEPLOYMENT_PREFIX}}
         EMAIL_HOST=${{ secrets.EMAIL_HOST}}
@@ -73,9 +71,9 @@ jobs:
         KAFKA_INSTANCE_TYPE=${{ secrets.KAFKA_INSTANCE_TYPE}}
         LOAD_TEST_MODE=${{ secrets.LOAD_TEST_MODE}}
         LOGO_URL=${{ secrets.LOGO_URL}}
-        NEW_RELIC_APP_NAME=${{ secrets.TEST_NEW_RELIC_APP_NAME}}
+        NEW_RELIC_APP_NAME=${{ secrets.NEW_RELIC_APP_NAME}}
         NEW_RELIC_ENABLED=${{ secrets.NEW_RELIC_ENABLED}}
-        NEW_RELIC_LICENSE_KEY=${{ secrets.TEST_NEW_RELIC_LICENSE_KEY}}
+        NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY}}
         NEW_RELIC_LOG_LEVEL=${{ secrets.NEW_RELIC_LOG_LEVEL}}
         NODE_ENV=${{ secrets.NODE_ENV}}
         OAUTH_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID}}
@@ -83,19 +81,19 @@ jobs:
         OAUTH_REFRESH_TOKEN=${{ secrets.OAUTH_REFRESH_TOKEN}}
         ONESIGNAL_API_KEY=${{ secrets.ONESIGNAL_API_KEY}}
         ONESIGNAL_APP_ID=${{ secrets.ONESIGNAL_APP_ID}}
-        REDIS_HOST=${{ secrets.TEST_REDIS_HOST}}
-        REDIS_PASSWORD=${{ secrets.TEST_REDIS_PASSWORD}}
-        REDIS_PORT=${{ secrets.TEST_REDIS_PORT}}
-        REDIS_URL=${{ secrets.TEST_REDIS_URL}}
-        REDIS_USERNAME=${{ secrets.TEST_REDIS_USERNAME}}
+        REDIS_HOST=${{ secrets.REDIS_HOST}}
+        REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD}}
+        REDIS_PORT=${{ secrets.REDIS_PORT}}
+        REDIS_URL=${{ secrets.REDIS_URL}}
+        REDIS_USERNAME=${{ secrets.REDIS_USERNAME}}
         SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY}}
         SU_HOST_EMAIL_1=${{ secrets.SU_HOST_EMAIL_1}}
         SU_HOST_EMAIL_2=${{ secrets.SU_HOST_EMAIL_2}}
         SU_HOST_EMAIL_3=${{ secrets.SU_HOST_EMAIL_3}}
         KAFKA_LOGS=${{ secrets.KAFKA_LOGS}}
         KAFKA_REGION=${{ secrets.KAFKA_REGION}}
-        KAFKA_BROKER=${{ secrets.TEST_KAFKA_BROKER}}
-        KAFKA_CLIENT_ID=${{ secrets.TEST_KAFKA_CLIENT_ID}}
+        KAFKA_BROKER=${{ secrets.KAFKA_BROKER}}
+        KAFKA_CLIENT_ID=${{ secrets.KAFKA_CLIENT_ID}}
         KAFKA_PASSWORD=${{ secrets.KAFKA_PASSWORD}}
         KAFKA_INSTANCE_TYPE=${{ secrets.KAFKA_INSTANCE_TYPE}}
         KAFKA_USERNAME=${{ secrets.KAFKA_USERNAME}}
@@ -154,7 +152,6 @@ jobs:
         echo "DB_HOST=$DB_HOST" >> .env
         echo "DB_NAME=$DB_NAME" >> .env
         echo "DB_PASS=$DB_PASS" >> .env
-        echo "DB_PORT=$DB_PORT" >> .env
         echo "DB_PASSWORD=$DB_PASSWORD" >> .env
         echo "DB_USER_NAME=$DB_USER_NAME" >> .env
         echo "DEFAULT_ELECTRICITY_PROVIDER=$DEFAULT_ELECTRICITY_PROVIDER" >> .env
@@ -170,7 +167,7 @@ jobs:
         echo "LOAD_TEST_MODE=$LOAD_TEST_MODE" >> .env
         echo "LOGO_URL=$LOGO_URL" >> .env
         echo "NEW_RELIC_APP_NAME=$NEW_RELIC_APP_NAME" >> .env
-        echo "NEW_RELIC_LOG_ENABLED=$NEW_RELIC_ENABLED" >> .env
+        echo "NEW_RELIC_ENABLED=$NEW_RELIC_ENABLED" >> .env
         echo "NEW_RELIC_LICENSE_KEY=$NEW_RELIC_LICENSE_KEY" >> .env
         echo "NEW_RELIC_LOG_LEVEL=$NEW_RELIC_LOG_LEVEL" >> .env
         echo "NODE_ENV=$NODE_ENV" >> .env
@@ -188,11 +185,10 @@ jobs:
         echo "SU_HOST_EMAIL_1=$SU_HOST_EMAIL_1" >> .env
         echo "SU_HOST_EMAIL_2=$SU_HOST_EMAIL_2" >> .env
         echo "SU_HOST_EMAIL_3=$SU_HOST_EMAIL_3" >> .env
-        echo "NODE_TLS_REJECT_UNAUTHORIZED=0" >> .env
         cat .env
     - name: push to state to s3
       run: |
-        cp ./.env prod.env
+        cp .env prod.env
         aws s3 cp ./prod.env s3://accuvend-bucket-configuration/ 
     - name: Save env file
       uses: actions/cache@v2
@@ -204,7 +200,7 @@ jobs:
   scan-backend: 
     name: scan-backend
     runs-on: ubuntu-latest
-    if : github.ref == 'refs/heads/build'
+    if : github.ref == 'refs/heads/sandbox'
     # needs: [test-backend]
     needs: [generate-env-file]
     steps: 
@@ -228,7 +224,7 @@ jobs:
   build-backend:
     name: build-backend
     needs: [scan-backend]
-    if : github.ref == 'refs/heads/build'
+    if : github.ref == 'refs/heads/sandbox'
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -280,7 +276,7 @@ jobs:
   push-build:
     name: push-build
     needs: [build-backend]
-    if : github.ref == 'refs/heads/build'
+    if : github.ref == 'refs/heads/sandbox'
     runs-on: ubuntu-latest
     steps:
       - name: chechkout
@@ -311,14 +307,14 @@ jobs:
           fi
           unzip dist.zip 
           ls -R dist
-          cp ./dist.zip testdist.zip
-          aws s3 cp ./testdist.zip s3://staging-bucket-deployment/ 
+          cp ./dist.zip proddist.zip
+          aws s3 cp ./dist.zip s3://staging-bucket-deployment/ 
 
-  # Depolys the backend to build
+  # Depolys the backend to sandbox
   deploy-build:
     name: deploy-build
     needs: [push-build]
-    if : github.ref == 'refs/heads/build'
+    if : github.ref == 'refs/heads/sandbox'
     runs-on: ubuntu-latest
     steps:
       - name: chechkout
@@ -337,7 +333,7 @@ jobs:
       - name: get ip address for staging ec2
         id: get_ip_address_ec2
         run: |
-          EC2_HOST_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=Test-core-engine" --query "Reservations[].Instances[].[PublicIpAddress]" --output text)
+          EC2_HOST_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=Sand Box (Prod) Core Instance" --query "Reservations[].Instances[].[PublicIpAddress]" --output text)
           echo "EC2_HOST_IP=$EC2_HOST_IP" >> $GITHUB_OUTPUT
       - name: SSH to EC2 Instance
         env: 
@@ -351,13 +347,13 @@ jobs:
             cd /home/ubuntu/
             pm2 stop server #stop the server 
             # GET THE LATEST_SUCCESSFUL_RUN_ID 
-            if aws s3 cp s3://accuvend-bucket-configuration/test_staging_last_run.txt ./test_staging_last_run.txt | grep "does not exist" 
+            if aws s3 cp s3://accuvend-bucket-configuration/staging_last_run.txt ./staging_last_run.txt | grep "does not exist" 
             then
                 echo 'FILE DOES NOT EXIST'
                 LAST_SUCCESSFUL_RUN_NUMBER=0               
             else
                 echo 'FILE EXIST'
-                LAST_SUCCESSFUL_RUN_NUMBER=$(grep LAST_SUCCESSFUL_RUN_ID ./test_staging_last_run.txt | cut -d "=" -f2)            
+                LAST_SUCCESSFUL_RUN_NUMBER=$(grep LAST_SUCCESSFUL_RUN_ID ./staging_last_run.txt | cut -d "=" -f2)            
             fi
             #rename the old folder 
             echo "$LAST_SUCCESSFUL_RUN_NUMBER"
@@ -368,34 +364,35 @@ jobs:
                 echo "Folder does not exist."
             fi
             # download build latest
-            aws s3 cp s3://staging-bucket-deployment/testdist.zip dist.zip
+            aws s3 cp s3://staging-bucket-deployment/proddist.zip dist.zip
             #unzip latest build
             unzip dist.zip
             # cd 
             cd dist
 
             # Get ENV file
-            aws s3 cp s3://accuvend-bucket-configuration/prod.env ./.env
+            aws s3 cp s3://accuvend-bucket-configuration/.env ./.env
             
             #GET DATABASE CREDENTINALS
             DB_USERNAME=$(grep DB_USER_NAME ./.env | cut -d "=" -f2) &&\
             DB_PASSWORD=$(grep DB_PASSWORD ./.env | cut -d "=" -f2) &&\
             DB_NAME=$(grep DB_DB_NAME ./.env | cut -d "=" -f2) &&\
-            DB_PORT=$(grep DB_PORT ./.env | cut -d "=" -f2) &&\
-            DB_HOST=$(grep DB_HOST ./.env | cut -d "=" -f2)
-          
-            echo "DB_URL=postgres://$DB_USERNAME:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=require" >> .env
-            echo "LOG_DB_URL=postgres://$DB_USERNAME:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=require" >> .env
+            DB_HOST=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=Sand Box (Prod) DB Instance 1" --query "Reservations[].Instances[].[PublicIpAddress]" --output text)
+            LOG_DB_HOST=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=Sand Box (Prod) DB Instance 2" --query "Reservations[].Instances[].[PublicIpAddress]" --output text)
+            
+            echo "DB_URL=postgres://$DB_USERNAME:$DB_PASSWORD@$DB_HOST:5432/$DB_NAME" >> .env
+            echo "LOG_DB_URL=postgres://$DB_USERNAME:$DB_PASSWORD@$LOG_DB_HOST:5432/$DB_NAME" >> .env
+            
             #install depencendies in dist folder
             npm install
             
             #Set up restart server 
-            pm2 start server.js --time'
+            pm2 start server.js --time -i max '
           
   # Smoke Test to check if server is up and running 
   smoke-test:
     name: smoke-test
-    if : github.ref == 'refs/heads/build'
+    if : github.ref == 'refs/heads/sandbox'
     runs-on: ubuntu-latest
     needs: [deploy-build]
     outputs:
@@ -410,9 +407,8 @@ jobs:
     - name: check if server is up and running 
       id: check_server_status
       run : |
-        EC2_HOST_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=Test-core-engine" --query "Reservations[].Instances[].[PublicIpAddress]" --output text)
-        sleep 30 # wait 30 seconds to make sure the server is up and running before somke test 
-        echo "http://${EC2_HOST_IP}/healthcheck"
+        EC2_HOST_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=Sand Box (Prod) Core Instance" --query "Reservations[].Instances[].[PublicIpAddress]" --output text)
+        sleep 10 # wait 10 seconds to make sure the server is up and running before somke test 
         if curl "http://${EC2_HOST_IP}/healthcheck" | grep "Server is working"
         then
             echo "SMOKE_TEST_RESULT PASSED"
@@ -428,7 +424,7 @@ jobs:
   roll-back:
     name: roll-back
     needs: smoke-test
-    if : github.ref == 'refs/heads/build'
+    if : github.ref == 'refs/heads/sandbox'
     runs-on: ubuntu-latest
     steps: 
       - name: Configure AWS Credentials
@@ -442,7 +438,7 @@ jobs:
           PRIVATE_KEY: ${{ secrets.SAND_BOX_SSH_KEY }}
           GITHUB_RUN_NUMBER: ${{ secrets.GITHUB_RUN_NUMBER }}
         run: |
-          EC2_HOST_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=Test-core-engine" --query "Reservations[].Instances[].[PublicIpAddress]" --output text)
+          EC2_HOST_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=Sand Box (Prod) Core Instance" --query "Reservations[].Instances[].[PublicIpAddress]" --output text)
           echo "${{needs.smoke-test.outputs.smoke_test_result}}"
           if [[ "${{needs.smoke-test.outputs.smoke_test_result}}" == "1" ]];
           then 
@@ -454,13 +450,13 @@ jobs:
               cd /home/ubuntu/
               pm2 stop server #stop the server 
               # GET THE LATEST_SUCCESSFUL_RUN_ID 
-              if aws s3 cp s3://accuvend-bucket-configuration/test_staging_last_run.txt ./test_staging_last_run.txt | grep "does not exist" 
+              if aws s3 cp s3://accuvend-bucket-configuration/staging_last_run.txt ./staging_last_run.txt | grep "does not exist" 
               then
                   echo 'FILE DOES NOT EXIST'
                   LAST_SUCCESSFUL_RUN_NUMBER=0               
               else
                   echo 'FILE EXIST'
-                  LAST_SUCCESSFUL_RUN_NUMBER=$(grep LAST_SUCCESSFUL_RUN_ID ./test_staging_last_run.txt | cut -d "=" -f2)            
+                  LAST_SUCCESSFUL_RUN_NUMBER=$(grep LAST_SUCCESSFUL_RUN_ID ./staging_last_run.txt | cut -d "=" -f2)            
               fi
               #rename the old folder 
               echo "$LAST_SUCCESSFUL_RUN_NUMBER"
@@ -475,13 +471,13 @@ jobs:
               cd dist
               
               #Set up server 
-              pm2 start server.js --time'
+              pm2 start server.js --time -i max'
             
           fi 
   # Fail stage initiate on successful roll back 
   fail-stage-on-rollback: 
     name:  fail-stage-on-rollback
-    if : github.ref == 'refs/heads/build'
+    if : github.ref == 'refs/heads/sandbox'
     needs: [roll-back, smoke-test ]
     runs-on: ubuntu-latest
     steps: 
@@ -500,8 +496,8 @@ jobs:
   # Clean up of old artificats on successful deployment 
   clean-up:
     name: clean-up
-    needs: [roll-back, smoke-test ]
-    if : github.ref == 'refs/heads/build'
+    needs: [roll-back, smoke-test]
+    if : github.ref == 'refs/heads/sandbox'
     runs-on: ubuntu-latest
     steps: 
       - name: Configure AWS Credentials
@@ -539,7 +535,7 @@ jobs:
           PRIVATE_KEY: ${{ secrets.SAND_BOX_SSH_KEY }}
           GITHUB_RUN_NUMBER: ${{ secrets.GITHUB_RUN_NUMBER }}
         run: |
-          EC2_HOST_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=Test-core-engine" --query "Reservations[].Instances[].[PublicIpAddress]" --output text)
+          EC2_HOST_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=Sand Box (Prod) Core Instance" --query "Reservations[].Instances[].[PublicIpAddress]" --output text)
           echo "${{needs.smoke-test.outputs.smoke_test_result}}"
           if [[ "${{needs.smoke-test.outputs.smoke_test_result}}" == "1" ]];
           then 
@@ -549,13 +545,13 @@ jobs:
               cd /home/ubuntu/
               pm2 stop server #stop the server 
               # GET THE LATEST_SUCCESSFUL_RUN_ID 
-              if aws s3 cp s3://accuvend-bucket-configuration/test_staging_last_run.txt ./test_staging_last_run.txt | grep "does not exist" 
+              if aws s3 cp s3://accuvend-bucket-configuration/staging_last_run.txt ./staging_last_run.txt | grep "does not exist" 
               then
                   echo 'FILE DOES NOT EXIST'
                   LAST_SUCCESSFUL_RUN_NUMBER=0               
               else
                   echo 'FILE EXIST'
-                  LAST_SUCCESSFUL_RUN_NUMBER=$(grep LAST_SUCCESSFUL_RUN_ID ./test_staging_last_run.txt | cut -d "=" -f2)            
+                  LAST_SUCCESSFUL_RUN_NUMBER=$(grep LAST_SUCCESSFUL_RUN_ID ./staging_last_run.txt | cut -d "=" -f2)            
               fi
               #delete the old folder 
               echo "$LAST_SUCCESSFUL_RUN_NUMBER"
@@ -569,7 +565,7 @@ jobs:
               cd dist
               
               #Set up restart server 
-              pm2 start server.js --time '
+              pm2 start server.js --time -i max'
           else
             echo "Rolled back No Cleanup"
             exit 1
@@ -577,8 +573,8 @@ jobs:
   # Add RUN_id has last successful run
   save-latest-successful_run:
     name: save-latest-successful-run
-    # if : github.ref == 'refs/heads/build' && needs.smoke-test.outputs.smoke_test_result == '1'
-    if : github.ref == 'refs/heads/build'
+    # if : github.ref == 'refs/heads/sandbox' && needs.smoke-test.outputs.smoke_test_result == '1'
+    if : github.ref == 'refs/heads/sandbox'
     needs: [fail-stage-on-rollback , clean-up]
     # needs: [roll-back, smoke-test]
     runs-on: ubuntu-latest
@@ -594,13 +590,13 @@ jobs:
           PRIVATE_KEY: ${{ secrets.SAND_BOX_SSH_KEY }}
           GITHUB_RUN_NUMBER: ${{ secrets.GITHUB_RUN_NUMBER }}
         run: |
-          echo "LAST_SUCCESSFUL_RUN_ID=$GITHUB_RUN_NUMBER" > test_staging_last_run.txt
-          aws s3 cp ./test_staging_last_run.txt s3://accuvend-bucket-configuration/test_staging_last_run.txt
+          echo "LAST_SUCCESSFUL_RUN_ID=$GITHUB_RUN_NUMBER" > staging_last_run.txt
+          aws s3 cp ./staging_last_run.txt s3://accuvend-bucket-configuration/staging_last_run.txt
         
   # create-update-environment:
   #   name: create-environment
   #   needs: [push-build]
-  #   if : github.ref == 'refs/heads/build'
+  #   if : github.ref == 'refs/heads/sandbox'
   #   runs-on: ubuntu-latest
   #   steps:
   #   - name: Checkout
@@ -613,13 +609,13 @@ jobs:
   #       aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
   #   - name: pull terraform state from s3
   #     run: |
-  #       aws s3 cp s3://build-terraform-item/terraform.tfstate ./terraform/build && echo "Success: The AWS CLI command completed successfully." || echo "Error: The AWS CLI command failed."
+  #       aws s3 cp s3://sandbox-terraform-item/terraform.tfstate ./terraform/sandbox && echo "Success: The AWS CLI command completed successfully." || echo "Error: The AWS CLI command failed."
     
   #   - name: Terraform Setup
   #     uses: hashicorp/setup-terraform@v3
   #     env:
   #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #       TF_ACTION_WORKING_DIR: 'terraform/build'
+  #       TF_ACTION_WORKING_DIR: 'terraform/sandbox'
   #       TF_AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
   #       TF_AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   #       TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -632,12 +628,12 @@ jobs:
   #       TF_VAR_image_id: ${{secrets.IMAGE_ID}}
   #       TF_VAR_instance_type: ${{secrets.INSTANCE_TYPE}}
   #       TF_VAR_kafka_instance_type: "kafka.t3.small"
-  #       TF_VAR_instance_keypair: "build-key-pair"
+  #       TF_VAR_instance_keypair: "sandbox-key-pair"
       
   #   - name: Terraform fmt
   #     id: fmt
   #     run: | 
-  #        cd terraform/build
+  #        cd terraform/sandbox
   #        pwd
   #        terraform fmt -check
   #     continue-on-error: true
@@ -645,21 +641,21 @@ jobs:
   #   - name: Terraform Init
   #     id: init
   #     run:  | 
-  #        cd terraform/build
+  #        cd terraform/sandbox
   #        pwd
   #        terraform init
     
   #   - name: Terraform Validate
   #     id: validate
   #     run:  | 
-  #        cd terraform/build
+  #        cd terraform/sandbox
   #        pwd
   #        terraform validate -no-color
     
   #   - name: Terraform Plan
   #     id: plan
   #     run:  | 
-  #        cd terraform/build
+  #        cd terraform/sandbox
   #        pwd
   #        terraform plan -no-color
   #     continue-on-error: true
@@ -667,7 +663,7 @@ jobs:
   #   - name: Terraform apply
   #     id: apply
   #     run: |
-  #         cd terraform/build
+  #         cd terraform/sandbox
   #         pwd
   #         terraform apply -auto-approve -no-color
   #     continue-on-error: true
@@ -681,9 +677,9 @@ jobs:
 
   #   - name: Save tft.state file 
   #     run: |
-  #         cd terraform/build
+  #         cd terraform/sandbox
   #         pwd
-  #         aws s3 cp terraform.tfstate s3://build-terraform-item/
+  #         aws s3 cp terraform.tfstate s3://sandbox-terraform-item/
       
    
       
